name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'
      
      
    - name: Install and Build
      run: |
        npm install
        npm run build
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages  # The branch the action should deploy to.
        folder: build  # The folder the action should deploy.
        token: ${{ secrets.TURINGGRADIENT}}  # GitHub automatically creates a secret token that is used by Actions.
